#!/bin/bash

# Autor: Sebastián Vico Guzmán

i=1
while [ ${i} -le ${#} ]
do
	echo ${i} # Muestra el valor de i
	echo ${!i} # Muestra el valor de cada parametro posicional
	echo ${!#} # Muestra el valor del ultimo parametro
	i=$(( ${i} + 1 )) # Incremento i
done
