#!/bin/bash

# Autor: Sebastián Vico Guzmán
# Descripcion: Usa alguna variables para demostrar su uso

var1=hola
var2=1+2
var3=${1}

echo El contenido de var1 es: ${var1}
echo El contenido de var2 es: ${var2}
echo El contenido de var3 es: ${var3}
